'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace dnnWerk.Modules.Nuntio.Articles

    Partial Public Class uc_ThreadedList

        '''<summary>
        '''radcodeblock control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radcodeblock As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''ctlAjax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAjax As Global.Telerik.Web.UI.RadAjaxPanel

        '''<summary>
        '''chkIsSearchResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsSearchResult As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ctlSplitContainer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlSplitContainer As Global.Telerik.Web.UI.RadSplitter

        '''<summary>
        '''ctlToc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlToc As Global.Telerik.Web.UI.RadPane

        '''<summary>
        '''ctlTools control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlTools As Global.Telerik.Web.UI.RadToolBar

        '''<summary>
        '''CategoriesTree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CategoriesTree As Global.Telerik.Web.UI.RadTreeView

        '''<summary>
        '''CategoriesMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CategoriesMenu As Global.Telerik.Web.UI.RadTreeViewContextMenu

        '''<summary>
        '''ArticlesMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ArticlesMenu As Global.Telerik.Web.UI.RadTreeViewContextMenu

        '''<summary>
        '''ctlBar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlBar As Global.Telerik.Web.UI.RadSplitBar

        '''<summary>
        '''ctlContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlContent As Global.Telerik.Web.UI.RadPane

        '''<summary>
        '''dvSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ctlSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlSearch As Global.dnnWerk.Modules.Nuntio.Articles.uc_Search

        '''<summary>
        '''plhItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plhItem As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''ctlFrame control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlFrame As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lpPaging control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lpPaging As Global.Telerik.Web.UI.RadAjaxLoadingPanel

        '''<summary>
        '''wndControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents wndControls As Global.Telerik.Web.UI.RadWindowManager
    End Class
End Namespace
