'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace dnnWerk.Modules.Nuntio.Articles

    Partial Public Class Window

        '''<summary>
        '''Head control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Head As Global.System.Web.UI.HtmlControls.HtmlHead

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''CSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CSS As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''frmWindow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmWindow As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''plhControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plhControls As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''ScrollTop control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScrollTop As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''__dnnVariable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents __dnnVariable As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
