'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace dnnWerk.Modules.Nuntio.Articles

    Partial Public Class uc_RotateSettings

        '''<summary>
        '''plTheme control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTheme As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpThemes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpThemes As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plSelectNewsModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSelectNewsModule As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboModules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboModules As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblNoModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoModule As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCategories As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''treeCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents treeCategories As Global.Telerik.Web.UI.RadTreeView

        '''<summary>
        '''plRowCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRowCount As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRowCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRowCount As Global.Telerik.Web.UI.RadNumericTextBox

        '''<summary>
        '''rowShowFutureItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowShowFutureItems As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plShowFutureItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowFutureItems As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkShowFutureItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowFutureItems As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowPastItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowPastItems As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkShowPastItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowPastItems As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowSortOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowSortOrder As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSortOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSortOrder As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblSortOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSortOrder As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plUseOriginalVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUseOriginalVersion As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkUseOriginalVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUseOriginalVersion As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plScrollHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plScrollHeight As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtScrollHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtScrollHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plScrollWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plScrollWidth As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtScrollWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtScrollWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plScrollTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plScrollTimeout As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtScrollTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtScrollTimeout As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plScrollSpeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plScrollSpeed As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtScrollSpeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtScrollSpeed As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plScrollDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plScrollDirection As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpScrollDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpScrollDirection As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plModuletitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModuletitle As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plhModultitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plhModultitle As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVersion As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
