'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:2.0.50727.4927
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace dnnWerk.Modules.Nuntio.Articles

    Partial Public Class uc_CategoryBrowser

        '''<summary>
        '''CategoriesTree-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents CategoriesTree As Global.Telerik.Web.UI.RadTreeView
    End Class
End Namespace
