'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace dnnWerk.Modules.Nuntio.Articles

    Partial Public Class uc_AuthorBrowserSettings

        '''<summary>
        '''plSelectNewsModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSelectNewsModule As Global.System.Web.UI.UserControl

        '''<summary>
        '''cboModules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboModules As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblNoModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoModule As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plSkin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSkin As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpSkin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSkin As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plIncludeRoot control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIncludeRoot As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIncludeRoot control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludeRoot As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowLines control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowLines As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowLines control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowLines As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowFolderIcon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowFolderIcon As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowFolderIcon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowFolderIcon As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowNumbers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowNumbers As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowNumbers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowNumbers As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowFutureItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowFutureItems As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowFutureItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowFutureItems As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowPastItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowPastItems As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowPastItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowPastItems As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plIncludeExpired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIncludeExpired As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIncludeExpired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludeExpired As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plModuletitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModuletitle As Global.System.Web.UI.UserControl

        '''<summary>
        '''plhModultitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plhModultitle As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
