'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace dnnWerk.Modules.Nuntio.Articles

    Partial Public Class uc_ListSettings

        '''<summary>
        '''plTheme control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTheme As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpThemes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpThemes As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plSelectNewsModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSelectNewsModule As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboModules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboModules As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCategories As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''treeCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents treeCategories As Global.Telerik.Web.UI.RadTreeView

        '''<summary>
        '''plRowCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRowCount As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRowCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRowCount As Global.Telerik.Web.UI.RadNumericTextBox

        '''<summary>
        '''rowPaging control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowPaging As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plEnablePaging control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnablePaging As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnablePaging control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnablePaging As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowPagingMaxCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowPagingMaxCount As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPagingMaxCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPagingMaxCount As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPagingMaxCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPagingMaxCount As Global.Telerik.Web.UI.RadNumericTextBox

        '''<summary>
        '''rowIncludePublications control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowIncludePublications As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plIncludePublications control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIncludePublications As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkIncludePublications control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludePublications As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowIncludeNonPublications control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowIncludeNonPublications As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plIncludeNonPublications control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIncludeNonPublications As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkIncludeNonPublications control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludeNonPublications As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowShowFutureItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowShowFutureItems As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plShowFutureItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowFutureItems As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkShowFutureItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowFutureItems As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowShowPastItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowShowPastItems As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plShowPastItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowPastItems As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkShowPastItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowPastItems As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowShowFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowShowFeatured As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plShowFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowFeatured As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkShowFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowFeatured As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowShowNonFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowShowNonFeatured As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plShowNonFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowNonFeatured As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkShowNonFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowNonFeatured As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowMakeFeaturedSticky control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowMakeFeaturedSticky As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plMakeFeaturedSticky control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMakeFeaturedSticky As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkMakeFeaturedSticky control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkMakeFeaturedSticky As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowSortOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowSortOrder As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSortOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSortOrder As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblSortOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSortOrder As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plUseOriginalVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUseOriginalVersion As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkUseOriginalVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUseOriginalVersion As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowSearch As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSearch As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnableDnnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableDnnSearch As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkEnableModuleSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableModuleSearch As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowEnableSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowEnableSummary As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plEnableSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableSummary As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnableSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableSummary As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowModerate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowModerate As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plModerateNews control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModerateNews As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkModerateNews control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkModerateNews As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowModeratorRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowModeratorRole As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plModeratorRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModeratorRole As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpModeratorRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpModeratorRole As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rowAuthorizedRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowAuthorizedRoles As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAuhorizedRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAuhorizedRoles As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAuthorizedRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAuthorizedRoles As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''rowEnforceEditPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowEnforceEditPermissions As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plEnforceEditPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnforceEditPermissions As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnforceEditPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnforceEditPermissions As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowAllowTwitter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowAllowTwitter As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAllowTwitter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAllowTwitter As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAllowTwitter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowTwitter As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowAllowSubscriptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowAllowSubscriptions As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAllowSubscriptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAllowSubscriptions As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAllowSubscriptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowSubscriptions As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowNotificationDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowNotificationDebug As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plNotificationDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNotificationDebug As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkNotificationDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkNotificationDebug As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowOnlyRegisteredUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowOnlyRegisteredUsers As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plOnlyRegisteredUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plOnlyRegisteredUsers As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkOnlyRegisteredUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkOnlyRegisteredUsers As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowNotifyAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowNotifyAdmin As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plNotifyAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNotifyAdmin As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkNotifyAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkNotifyAdmin As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowFromAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowFromAddress As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plFromAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFromAddress As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtFromAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFromAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rowAutoSubscribedRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowAutoSubscribedRoles As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAutoSubscribeRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAutoSubscribeRoles As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAutoSubscribeRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAutoSubscribeRoles As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''rowAnonymousComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowAnonymousComments As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAnonymousComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAnonymousComments As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAnonymousComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAnonymousComments As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowAutoApproveAnonymousComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowAutoApproveAnonymousComments As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAutoApproveAnonymousComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAutoApproveAnonymousComments As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAutoApproveAnonymousComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAutoApproveAnonymousComments As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowAutoApproveAuthenticatedComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowAutoApproveAuthenticatedComments As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAutoApproveAuthenticatedComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAutoApproveAuthenticatedComments As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAutoApproveAuthenticatedComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAutoApproveAuthenticatedComments As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowJournal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowJournal As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAddToJournal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAddToJournal As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAddToJournal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAddToJournal As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plModuletitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModuletitle As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plhModultitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plhModultitle As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVersion As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
