'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:2.0.50727.4952
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace dnnWerk.Modules.Nuntio.Articles

    Partial Public Class uc_ArchiveSettings

        '''<summary>
        '''plSelectNewsModule-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents plSelectNewsModule As Global.System.Web.UI.UserControl

        '''<summary>
        '''cboModules-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents cboModules As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblNoModule-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents lblNoModule As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plSkin-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents plSkin As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpSkin-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents drpSkin As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plIncludeMonth-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents plIncludeMonth As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIncludeMonth-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents chkIncludeMonth As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plIncludeRoot-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents plIncludeRoot As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIncludeRoot-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents chkIncludeRoot As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowLines-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents plShowLines As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowLines-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents chkShowLines As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowFolderIcon-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents plShowFolderIcon As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowFolderIcon-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents chkShowFolderIcon As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowFutureItems-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents plShowFutureItems As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowFutureItems-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents chkShowFutureItems As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowPastItems-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents plShowPastItems As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowPastItems-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents chkShowPastItems As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowNumbers-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents plShowNumbers As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowNumbers-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents chkShowNumbers As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plModuletitle-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents plModuletitle As Global.System.Web.UI.UserControl

        '''<summary>
        '''plhModultitle-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents plhModultitle As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''cmdUpdate-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
