'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace dnnWerk.Modules.Nuntio.Articles

    Partial Public Class uc_Comment

        '''<summary>
        '''RadScriptBlock1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

        '''<summary>
        '''pnlResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlResult As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''btnTryAgain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnTryAgain As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnClose1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnClose1 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlForm As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtComment As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtName As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''txtEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmail As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''lblGravatar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGravatar As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''btnSend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSend As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnClose2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnClose2 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''chkAuthorized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAuthorized As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''pnlNeedsApproval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlNeedsApproval As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblApprove control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblApprove As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlCommentBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCommentBy As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblCommentBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCommentBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlNotAuthorized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlNotAuthorized As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblNotAuthorized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotAuthorized As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnLogin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnRegister control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnRegister As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnClose3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnClose3 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ctlAjax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAjax As Global.Telerik.Web.UI.RadAjaxManager

        '''<summary>
        '''lpComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lpComment As Global.Telerik.Web.UI.RadAjaxLoadingPanel

        '''<summary>
        '''RadFormDecorator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadFormDecorator1 As Global.Telerik.Web.UI.RadFormDecorator
    End Class
End Namespace
