'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace dnnWerk.Modules.Nuntio.Articles

    Partial Public Class uc_Configure

        '''<summary>
        '''lblConfigure control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblConfigure As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnkConfigure control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkConfigure As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
