'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace dnnWerk.Modules.Nuntio.Articles

    Partial Public Class uc_Edit

        '''<summary>
        '''RadScriptBlock1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

        '''<summary>
        '''ctlAjax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAjax As Global.Telerik.Web.UI.RadAjaxManager

        '''<summary>
        '''ctlTools control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlTools As Global.Telerik.Web.UI.RadToolBar

        '''<summary>
        '''pnlForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlForm As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''txtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTitle As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''drpLocale control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpLocale As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''lblPublishDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPublishDate As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ctlPublishDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlPublishDate As Global.Telerik.Web.UI.RadDateTimePicker

        '''<summary>
        '''chkPublished control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPublished As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkOriginal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkOriginal As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkFeatured As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblExpiryDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExpiryDate As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ctlExpiryDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlExpiryDate As Global.Telerik.Web.UI.RadDateTimePicker

        '''<summary>
        '''lblReviewDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReviewDate As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ctlReviewDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlReviewDate As Global.Telerik.Web.UI.RadDateTimePicker

        '''<summary>
        '''ctlTabstrip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlTabstrip As Global.Telerik.Web.UI.RadTabStrip

        '''<summary>
        '''ctlTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlTabs As Global.Telerik.Web.UI.RadMultiPage

        '''<summary>
        '''tabBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabBody As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''tabSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabSummary As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''tabAdvanced control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabAdvanced As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''RadCodeBlock5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock5 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''lblArticleInformationHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblArticleInformationHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblArticleId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblArticleId As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblLastUpdated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastUpdated As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblAnchorNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAnchorNote As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''txtAnchor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAnchor As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''lblHeadCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeadCategories As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblCategoriesHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCategoriesHelp As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''dvCategoryTree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvCategoryTree As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''treeCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents treeCategories As Global.Telerik.Web.UI.RadTreeView

        '''<summary>
        '''FirstNode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FirstNode As Global.Telerik.Web.UI.RadTreeViewContextMenu

        '''<summary>
        '''CategoryNodes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CategoryNodes As Global.Telerik.Web.UI.RadTreeViewContextMenu

        '''<summary>
        '''tabNewsletter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabNewsletter As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''pnlQueue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlQueue As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''RadCodeBlock1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''lblEmailHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailHeader As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblMeilQueueHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMeilQueueHelp As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''chkAddToQueue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAddToQueue As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''RadCodeBlock6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock6 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''lblHeadLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeadLink As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblLinkHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLinkHelp As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''rblType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''pnlUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlUrl As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUrl As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''btnLinkSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLinkSelect As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''chkNewWindow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkNewWindow As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkTrackUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkTrackUsers As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkTrackClicks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkTrackClicks As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''pnlTwitter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTwitter As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''RadCodeBlock2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock2 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''lblTwitterHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTwitterHeader As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblTwitterHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTwitterHelp As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''chkTwitter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkTwitter As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblTwitterAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTwitterAccount As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''txtTwitterAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTwitterAccount As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''tabAttachments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabAttachments As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''pnlAttachmentsWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAttachmentsWarning As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblAttachmentsWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAttachmentsWarning As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlAttachmentsNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAttachmentsNote As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblAttachmentsIntro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAttachmentsIntro As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''Panel3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''grdAttachments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdAttachments As Global.Telerik.Web.UI.RadGrid

        '''<summary>
        '''cmdAddAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddAttachment As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tabImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabImages As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''pnlImagesWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlImagesWarning As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblImagesWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblImagesWarning As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlImagesNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlImagesNote As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblImagesIntro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblImagesIntro As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlImagesGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlImagesGrid As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''grdImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdImages As Global.Telerik.Web.UI.RadGrid

        '''<summary>
        '''cmdAddImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddImage As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tabRelated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabRelated As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''RadCodeBlock4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock4 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''lblPublicationsHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPublicationsHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblPublicationsIntro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPublicationsIntro As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlPublication control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPublication As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''drpPublicationMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpPublicationMode As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''lblBelongsTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBelongsTo As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''drpRelatedPublicationItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpRelatedPublicationItem As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''btnAddPublicationRelation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddPublicationRelation As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''treePublication control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents treePublication As Global.Telerik.Web.UI.RadTreeView

        '''<summary>
        '''RadCodeBlock3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock3 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''lblRelatedHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRelatedHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblRelatedIntro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRelatedIntro As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''Div1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''drpRelatedArticleItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpRelatedArticleItem As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''btnAddArticleRelation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddArticleRelation As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''ctlRelatedArticles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlRelatedArticles As Global.Telerik.Web.UI.RadListBox

        '''<summary>
        '''tabVersioning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabVersioning As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''pnlVersioning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlVersioning As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''rptVersions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptVersions As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''lpDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lpDefault As Global.Telerik.Web.UI.RadAjaxLoadingPanel

        '''<summary>
        '''lpUpdating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lpUpdating As Global.Telerik.Web.UI.RadAjaxLoadingPanel

        '''<summary>
        '''lpDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lpDelete As Global.Telerik.Web.UI.RadAjaxLoadingPanel

        '''<summary>
        '''wndManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents wndManager As Global.Telerik.Web.UI.RadWindowManager

        '''<summary>
        '''ctlImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlImages As Global.Telerik.Web.UI.RadDialogOpener

        '''<summary>
        '''ctlFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlFiles As Global.Telerik.Web.UI.RadDialogOpener

        '''<summary>
        '''ctlDMX control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlDMX As Global.Telerik.Web.UI.RadDialogOpener

        '''<summary>
        '''txtPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPath As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
