'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:2.0.50727.4927
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace dnnWerk.Modules.Nuntio.Articles

    Partial Public Class uc_Message

        '''<summary>
        '''RadScriptBlock1-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

        '''<summary>
        '''plhControls-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents plhControls As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''btnClose-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ctlAjax-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents ctlAjax As Global.Telerik.Web.UI.RadAjaxManager
    End Class
End Namespace
