'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace dnnWerk.Modules.Nuntio.Articles

    Partial Public Class uc_Publications

        '''<summary>
        '''ctlAjax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAjax As Global.Telerik.Web.UI.RadAjaxManager

        '''<summary>
        '''pnlTree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTree As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cmdNewPublication control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdNewPublication As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlCheck control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCheck As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''chkNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkNew As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ctlTree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlTree As Global.Telerik.Web.UI.RadTreeView

        '''<summary>
        '''pnlAddForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAddForm As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblIntro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIntro As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''drpRelatedPublicationItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpRelatedPublicationItem As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''btnAddPublicationRelation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddPublicationRelation As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lblResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlRemoveForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRemoveForm As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblRemove control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRemove As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''cmdRemove control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdRemove As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
