'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace dnnWerk.Modules.Nuntio.Articles

    Partial Public Class uc_Templates

        '''<summary>
        '''radSplitter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radSplitter As Global.Telerik.Web.UI.RadSplitter

        '''<summary>
        '''pane_Left control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pane_Left As Global.Telerik.Web.UI.RadPane

        '''<summary>
        '''LeftSlider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LeftSlider As Global.Telerik.Web.UI.RadSlidingZone

        '''<summary>
        '''pane_Help control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pane_Help As Global.Telerik.Web.UI.RadSlidingPane

        '''<summary>
        '''lblHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdTemplateHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdTemplateHelp As Global.Telerik.Web.UI.RadGrid

        '''<summary>
        '''pane_Tree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pane_Tree As Global.Telerik.Web.UI.RadSlidingPane

        '''<summary>
        '''pnlLeft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlLeft As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''tree_Skins control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tree_Skins As Global.Telerik.Web.UI.RadTreeView

        '''<summary>
        '''RadSplitBar1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadSplitBar1 As Global.Telerik.Web.UI.RadSplitBar

        '''<summary>
        '''Pane_Template control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Pane_Template As Global.Telerik.Web.UI.RadPane

        '''<summary>
        '''LoadingPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LoadingPanel As Global.Telerik.Web.UI.RadAjaxLoadingPanel

        '''<summary>
        '''lblUpdating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUpdating As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRight As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''TemplateTools control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TemplateTools As Global.Telerik.Web.UI.RadToolBar

        '''<summary>
        '''pnlFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlFiles As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''grdFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdFiles As Global.Telerik.Web.UI.RadGrid

        '''<summary>
        '''pnlEditor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEditor As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''txtTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlForm As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblCopy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCopy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rblMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblMode As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''cmdCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCreate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''RadAjaxManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadAjaxManager As Global.Telerik.Web.UI.RadAjaxManager
    End Class
End Namespace
